spring.application.name=leave-management-system

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/leave_management?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=cf9
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# IMPORTANT: disable Open Session in View
spring.jpa.open-in-view=false

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT Configuration
app.security.secret-key=T2ZmaWNpYWxMZWF2ZU1hbmFnZW1lbnRTeXN0ZW1TZWNyZXRLZXkyMDI2IQ==
app.security.jwt-expiration=900000
